# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lula < Formula
  desc "The Compliance Validator"
  homepage "https://lula.dev"
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/lula/releases/download/v0.13.0/lula_v0.13.0_Darwin_amd64"
      sha256 "81e499a19c01dfe2e62d1984dd4412f518571003e004b226794cc9b599367b79"

      def install
        bin.install "lula_v0.13.0_Darwin_amd64" => "lula"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/lula/releases/download/v0.13.0/lula_v0.13.0_Darwin_arm64"
      sha256 "3f9b1aa15d8db221dc9df9b564d68fe67fb9f8f53bca81e8e190d10037df0981"

      def install
        bin.install "lula_v0.13.0_Darwin_arm64" => "lula"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/lula/releases/download/v0.13.0/lula_v0.13.0_Linux_amd64"
        sha256 "ce66e4abfc78facc49445ec711322997187d9bd2ab066a3a7e6fc4762a220ca8"

        def install
          bin.install "lula_v0.13.0_Linux_amd64" => "lula"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/lula/releases/download/v0.13.0/lula_v0.13.0_Linux_arm64"
        sha256 "1a7c15fa6f154ece48cb39d306544e9f7a456a964e334144d641aac4c79efe98"

        def install
          bin.install "lula_v0.13.0_Linux_arm64" => "lula"
        end
      end
    end
  end
end
