# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LulaAT0150 < Formula
  desc "The Compliance Validator"
  homepage "https://lula.dev"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/lula/releases/download/v0.15.0/lula_v0.15.0_Darwin_amd64"
      sha256 "45806539a78d5fb76b11ebf239814347efcf52c170813cbedabe30f91b9c0974"

      def install
        bin.install "lula_v0.15.0_Darwin_amd64" => "lula"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/lula/releases/download/v0.15.0/lula_v0.15.0_Darwin_arm64"
      sha256 "885374a245d1d4fadaf2c0d9486d6620b41558cf1ac0af7facce8200268d5f68"

      def install
        bin.install "lula_v0.15.0_Darwin_arm64" => "lula"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/lula/releases/download/v0.15.0/lula_v0.15.0_Linux_amd64"
        sha256 "cb7cff41c7819fc92ee0c48041c5dcd69168a156b5cb00b45c2f402b1fed4ccf"

        def install
          bin.install "lula_v0.15.0_Linux_amd64" => "lula"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/lula/releases/download/v0.15.0/lula_v0.15.0_Linux_arm64"
        sha256 "7e2a116b9b5f0c849628dec876141ba3516aecee24ed90dc62778fceb953deba"

        def install
          bin.install "lula_v0.15.0_Linux_arm64" => "lula"
        end
      end
    end
  end
end
