# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maru < Formula
  desc "The Unicorn Task Runner"
  homepage "https://github.com/defenseunicorns/maru-runner"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.4.0/maru-runner_v0.4.0_Darwin_amd64"
      sha256 "fdd0054134c3e9510c8de990abb29a7ca89ca9e927f39c73f52581be9577ec5c"

      def install
        bin.install "maru-runner_v0.4.0_Darwin_amd64" => "maru"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.4.0/maru-runner_v0.4.0_Darwin_arm64"
      sha256 "ec6b843b190e210ed4ae120969a9df519f004ff9c721ec650eaa0942821a01f6"

      def install
        bin.install "maru-runner_v0.4.0_Darwin_arm64" => "maru"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.4.0/maru-runner_v0.4.0_Linux_amd64"
        sha256 "a4c7a7fd649272b4fd40b590b20e8a20f5651a3d86fefabc9947be7f3fa61e45"

        def install
          bin.install "maru-runner_v0.4.0_Linux_amd64" => "maru"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.4.0/maru-runner_v0.4.0_Linux_arm64"
        sha256 "1b18925e7afd46cecffef92878032d9ade4979082f8f8fb6a6a27692d816f8de"

        def install
          bin.install "maru-runner_v0.4.0_Linux_arm64" => "maru"
        end
      end
    end
  end
end
