# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maru2AT081 < Formula
  desc "A simple task runner"
  homepage "https://github.com/defenseunicorns/maru2"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/maru2/releases/download/v0.8.1/maru2_Darwin_x86_64.tar.gz"
      sha256 "d5499cdf764d8a01cd937230fc8390f647c22826f5507c7c58cfb3c2b5902a5f"

      def install
        bin.install "maru2"
        bin.install "maru2-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/maru2/releases/download/v0.8.1/maru2_Darwin_arm64.tar.gz"
      sha256 "0e3cf5ba5baf9d9424f35460b9f38a4d77381d67742bcc0f8af41c06e46783bb"

      def install
        bin.install "maru2"
        bin.install "maru2-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/maru2/releases/download/v0.8.1/maru2_Linux_x86_64.tar.gz"
      sha256 "09b741d3ce317bd327b0c69074e2f739f5dee36abdd73e592039ee8b9df4c4fa"
      def install
        bin.install "maru2"
        bin.install "maru2-publish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/maru2/releases/download/v0.8.1/maru2_Linux_arm64.tar.gz"
      sha256 "4ab45a32d4b74ce152e2f43929ddad954737273d7c559eab4116f2df9255df34"
      def install
        bin.install "maru2"
        bin.install "maru2-publish"
      end
    end
  end
end
