# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MaruATLatestRc < Formula
  desc "The Unicorn Task Runner"
  homepage "https://github.com/defenseunicorns/maru-runner"
  version "0.2.0-rc1"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.2.0-rc1/maru-runner_v0.2.0-rc1_Darwin_amd64"
      sha256 "22e09ad21913cc8d0fd4b415b310912ccb019220520dd6c3b8ada108d5cd941d"

      def install
        bin.install "maru-runner_v0.2.0-rc1_Darwin_amd64" => "maru"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.2.0-rc1/maru-runner_v0.2.0-rc1_Darwin_arm64"
      sha256 "7b6c15684827ae83b94a771478bc0ac505dd64fd32592962e69a6ae9da8188cd"

      def install
        bin.install "maru-runner_v0.2.0-rc1_Darwin_arm64" => "maru"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.2.0-rc1/maru-runner_v0.2.0-rc1_Linux_amd64"
        sha256 "5826e750f3ec8135484352b20ecc76323f44dad2397e22783710ff0700c0e747"

        def install
          bin.install "maru-runner_v0.2.0-rc1_Linux_amd64" => "maru"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/maru-runner/releases/download/v0.2.0-rc1/maru-runner_v0.2.0-rc1_Linux_arm64"
        sha256 "eb28d38832f77f7c36bc8abf13808f940732a7f722d25fafae2220d59f05837d"

        def install
          bin.install "maru-runner_v0.2.0-rc1_Linux_arm64" => "maru"
        end
      end
    end
  end
end
