# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0274 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.27.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.4/uds-cli_v0.27.4_Darwin_amd64"
      sha256 "2d59a1f9cf556867a3d73285d4e67752b754d186b34cd3cd4d92d3abdd435b84"

      def install
        bin.install "uds-cli_v0.27.4_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.4/uds-cli_v0.27.4_Darwin_arm64"
      sha256 "cefb4192509ca7d0b1fa80c864d0bf81d5ea7e8125a65a94abeb6474abac55ed"

      def install
        bin.install "uds-cli_v0.27.4_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.4/uds-cli_v0.27.4_Linux_amd64"
      sha256 "a117a78d752228b250d612672c7de8ce55c236fe4df19b4bb8e8df9c9dd51949"
      def install
        bin.install "uds-cli_v0.27.4_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.4/uds-cli_v0.27.4_Linux_arm64"
      sha256 "27fd0a6050b2489e940c09cf6b6774a2ff45585c43d055fd7157347b56d0bbda"
      def install
        bin.install "uds-cli_v0.27.4_Linux_arm64" => "uds"
      end
    end
  end
end
