# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0190 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.19.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.19.0/uds-cli_v0.19.0_Darwin_amd64"
      sha256 "f18e55419e33ecbbac272f2637953b47a2ad19c8f87efe0f2a9d08bbcbe534c1"

      def install
        bin.install "uds-cli_v0.19.0_Darwin_amd64" => "uds"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.19.0/uds-cli_v0.19.0_Darwin_arm64"
      sha256 "6b78ea8780e452f2678d363e3bb510f625f53530d0a56f6aff3f71be27303714"

      def install
        bin.install "uds-cli_v0.19.0_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.19.0/uds-cli_v0.19.0_Linux_amd64"
        sha256 "6f2a6c33f1c7b78645b83daf7e81813e0c980db9465c0c83d068ab3c8f4f279b"

        def install
          bin.install "uds-cli_v0.19.0_Linux_amd64" => "uds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.19.0/uds-cli_v0.19.0_Linux_arm64"
        sha256 "b44fd0de0fd4dcf629c914483700829d301d83b63b5fb1885eeaf89a24ce0dc0"

        def install
          bin.install "uds-cli_v0.19.0_Linux_arm64" => "uds"
        end
      end
    end
  end
end
