# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0220 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.22.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.22.0/uds-cli_v0.22.0_Darwin_amd64"
      sha256 "a6bcd99ac04c6c3015cf042db22a1593b8557e64302565513f84b534757623c9"

      def install
        bin.install "uds-cli_v0.22.0_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.22.0/uds-cli_v0.22.0_Darwin_arm64"
      sha256 "35f65c37ea42354185277d34eb5ca04092a1ecfacde90138151a300caa514493"

      def install
        bin.install "uds-cli_v0.22.0_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.22.0/uds-cli_v0.22.0_Linux_amd64"
        sha256 "16bf278c02e4d9d99d08e9d23e21f821daf8683318cdc704b04325de9c2e4240"

        def install
          bin.install "uds-cli_v0.22.0_Linux_amd64" => "uds"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.22.0/uds-cli_v0.22.0_Linux_arm64"
        sha256 "1c6ee6f73ea6fbec6d5e7d9d641548297b2ca977b8a8573dbb941e793dc7aaa0"

        def install
          bin.install "uds-cli_v0.22.0_Linux_arm64" => "uds"
        end
      end
    end
  end
end
