# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0012Alpha < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.0.12-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.12-alpha/uds-cli_v0.0.12-alpha_Darwin_amd64"
      sha256 "f3bf8ef34600b078e38f56c96d4035feda389767b2ee1c768a638a82c270e697"

      def install
        bin.install "uds-cli_v0.0.12-alpha_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.12-alpha/uds-cli_v0.0.12-alpha_Darwin_arm64"
      sha256 "4613e8a882f831d7e25dac8308adbf72f6446cb62ffd72a046066e4725e169a5"

      def install
        bin.install "uds-cli_v0.0.12-alpha_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.12-alpha/uds-cli_v0.0.12-alpha_Linux_amd64"
      sha256 "24c7ff4695bceaf716ddc4b701a993f0800933f5d99da078b58fe6aed74d00ad"

      def install
        bin.install "uds-cli_v0.0.12-alpha_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.12-alpha/uds-cli_v0.0.12-alpha_Linux_arm64"
      sha256 "cab3c19bfbd28fbc23dbe07d012bab15fc06849dc6e6dd13080e418558650c4f"

      def install
        bin.install "uds-cli_v0.0.12-alpha_Linux_arm64" => "uds"
      end
    end
  end
end
