# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0180 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.18.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.18.0/uds-cli_v0.18.0_Darwin_amd64"
      sha256 "c5d081e9b2ae077ea158d4ee9000e3199b24da403cd98c54d6c8a074a64e0a8c"

      def install
        bin.install "uds-cli_v0.18.0_Darwin_amd64" => "uds"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.18.0/uds-cli_v0.18.0_Darwin_arm64"
      sha256 "5822c911eed514026d79843455a292a6ff0177c37be0aa54719007d962e04c3d"

      def install
        bin.install "uds-cli_v0.18.0_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.18.0/uds-cli_v0.18.0_Linux_amd64"
        sha256 "3df6bf24a5e6a9ec1fcc387cfba9880fad31ec0a540c06dd05262c790985a7dc"

        def install
          bin.install "uds-cli_v0.18.0_Linux_amd64" => "uds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.18.0/uds-cli_v0.18.0_Linux_arm64"
        sha256 "8d069593673fb67d5bf736ce4e7026153dd7ec12c956ebd1304dc41567364839"

        def install
          bin.install "uds-cli_v0.18.0_Linux_arm64" => "uds"
        end
      end
    end
  end
end
