# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT061 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.6.1/uds-cli_v0.6.1_Darwin_arm64"
      sha256 "61f9daa67f1f8b7a8ce0a54fe600106ec24e66001dc57da3ab5a69b65b3b6e39"

      def install
        bin.install "uds-cli_v0.6.1_Darwin_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.6.1/uds-cli_v0.6.1_Darwin_amd64"
      sha256 "1a79844d68a02bb70a0ebb000cf81680ad9bf652f50fe1d2bd4c89a95c338548"

      def install
        bin.install "uds-cli_v0.6.1_Darwin_amd64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.6.1/uds-cli_v0.6.1_Linux_amd64"
      sha256 "7d704fc05e9fc5db1c153cf7e602a34626ea754e512bb09cb997dcebd8bdb1a9"

      def install
        bin.install "uds-cli_v0.6.1_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.6.1/uds-cli_v0.6.1_Linux_arm64"
      sha256 "fadf0ec895193b466c057fcadde6ea26b5fbe7f746c69818642ab388370e8412"

      def install
        bin.install "uds-cli_v0.6.1_Linux_arm64" => "uds"
      end
    end
  end
end
