# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT02718 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.27.18"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.18/uds-cli_v0.27.18_Darwin_amd64"
      sha256 "4c347c50bcfa72da52102170e00c9e5496cda14300b843987261e543882a4a09"

      def install
        bin.install "uds-cli_v0.27.18_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.18/uds-cli_v0.27.18_Darwin_arm64"
      sha256 "95039996e2ed8e04ab8e90039b60c4f0f161bcdea870323ea6152bbfd709c467"

      def install
        bin.install "uds-cli_v0.27.18_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.18/uds-cli_v0.27.18_Linux_amd64"
      sha256 "9abf516419b1db580236ccc844ef4ed63664524d669a2e412188dc55e535d852"
      def install
        bin.install "uds-cli_v0.27.18_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.18/uds-cli_v0.27.18_Linux_arm64"
      sha256 "dc53b33c0db583bfa097a7280dab771870bb093fa0ddeffc12065a4c97644bce"
      def install
        bin.install "uds-cli_v0.27.18_Linux_arm64" => "uds"
      end
    end
  end
end
