# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0104 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.10.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.10.4/uds-cli_v0.10.4_Darwin_amd64"
      sha256 "892064a9e8ad5618709dbf7ab86f22ee6b3a52936e74afaf1d3d6073ee7b3396"

      def install
        bin.install "uds-cli_v0.10.4_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.10.4/uds-cli_v0.10.4_Darwin_arm64"
      sha256 "cf8197839b1ca06890769f0cac91d5c6264a0195df5cabc683ea3dd51738fcf8"

      def install
        bin.install "uds-cli_v0.10.4_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.10.4/uds-cli_v0.10.4_Linux_amd64"
      sha256 "b22c5c75612ef6260ea6fb52583485d7560258072e894484e9b7a76920754889"

      def install
        bin.install "uds-cli_v0.10.4_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.10.4/uds-cli_v0.10.4_Linux_arm64"
      sha256 "7be35c0e9aa7c04865caf05c0d62d5884c9e36046463437ee38e37eca1495670"

      def install
        bin.install "uds-cli_v0.10.4_Linux_arm64" => "uds"
      end
    end
  end
end
