# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0110 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.11.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.0/uds-cli_v0.11.0_Darwin_amd64"
      sha256 "d46e77d1993222136aea77a03c2d9f4d74a9e1917f8239027067d39e6b44ec19"

      def install
        bin.install "uds-cli_v0.11.0_Darwin_amd64" => "uds"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.0/uds-cli_v0.11.0_Darwin_arm64"
      sha256 "f2a5599421c2ad24f64b726cbe2decf3f8c554a78eff53187e9b70268e075e5e"

      def install
        bin.install "uds-cli_v0.11.0_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.0/uds-cli_v0.11.0_Linux_amd64"
        sha256 "243a82202d904ef75625d2a4329aa6d1a91f2de006b97999f9f7f4e7c5fa36da"

        def install
          bin.install "uds-cli_v0.11.0_Linux_amd64" => "uds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.0/uds-cli_v0.11.0_Linux_arm64"
        sha256 "9d481b8e997fc0fd18f0915d4c3ab15ade3c3ae79c1e2733dddfc01e0f39e176"

        def install
          bin.install "uds-cli_v0.11.0_Linux_arm64" => "uds"
        end
      end
    end
  end
end
