# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0010Alpha < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.0.10-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.10-alpha/uds-cli_v0.0.10-alpha_Darwin_amd64"
      sha256 "3731e6addab5be731104a2193d60b6c8faf23f620d97f2159c17cf0209d8f21c"

      def install
        bin.install "uds-cli_v0.0.10-alpha_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.10-alpha/uds-cli_v0.0.10-alpha_Darwin_arm64"
      sha256 "618ec17e7c76bb404bdedafed233e8d9a44477f279d905ab6e5de45b3016d64d"

      def install
        bin.install "uds-cli_v0.0.10-alpha_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.10-alpha/uds-cli_v0.0.10-alpha_Linux_arm64"
      sha256 "27c3b4ec73a8c3953e7f3f2a819098e863e3e6e08669c016e7fb877bcc6cd253"

      def install
        bin.install "uds-cli_v0.0.10-alpha_Linux_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.10-alpha/uds-cli_v0.0.10-alpha_Linux_amd64"
      sha256 "536532b7ae09a24331136264ca1f5aad5be41ce925b573d02883bf4300ea2a4d"

      def install
        bin.install "uds-cli_v0.0.10-alpha_Linux_amd64" => "uds"
      end
    end
  end
end
