# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0351 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.35.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.35.1/uds-cli_v0.35.1_Darwin_amd64"
      sha256 "a80992cf9167a491f449d39806d867629734fd8c92fecc05cd0e44f4fc335c48"

      define_method(:install) do
        bin.install "uds-cli_v0.35.1_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.35.1/uds-cli_v0.35.1_Darwin_arm64"
      sha256 "2936937c065de9445a207ea08eb229b18c626f72d88e4719a977d27998c582ac"

      define_method(:install) do
        bin.install "uds-cli_v0.35.1_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.35.1/uds-cli_v0.35.1_Linux_amd64"
      sha256 "4ea7d553900199f36a4976bab526c780cac23a1025fb167e643d247682f252d4"
      define_method(:install) do
        bin.install "uds-cli_v0.35.1_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.35.1/uds-cli_v0.35.1_Linux_arm64"
      sha256 "0915934b29bf551929388fae5e661094e3643d2ceed5548d4c7d300f612f9b8e"
      define_method(:install) do
        bin.install "uds-cli_v0.35.1_Linux_arm64" => "uds"
      end
    end
  end
end
