# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0130 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.13.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.13.0/uds-cli_v0.13.0_Darwin_amd64"
      sha256 "77a289f4ffb033f0962d74b46b859713762605c40170e0acaf1479573bdf6146"

      def install
        bin.install "uds-cli_v0.13.0_Darwin_amd64" => "uds"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.13.0/uds-cli_v0.13.0_Darwin_arm64"
      sha256 "37b2dc85ada260af2dea9a3b4a77acf683dd2d68c51d56de82b6766bf0a1b3e6"

      def install
        bin.install "uds-cli_v0.13.0_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.13.0/uds-cli_v0.13.0_Linux_amd64"
        sha256 "3b7cbada2859efc4cc42e4f9ba501a665f818208accdc5f57524c6ab2ea309bf"

        def install
          bin.install "uds-cli_v0.13.0_Linux_amd64" => "uds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.13.0/uds-cli_v0.13.0_Linux_arm64"
        sha256 "207810e30b1b1e99dd3fa4caa66203c5c24c25c6fa457e06e784cf7427ad4308"

        def install
          bin.install "uds-cli_v0.13.0_Linux_arm64" => "uds"
        end
      end
    end
  end
end
