# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT092 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.9.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Darwin_arm64"
      sha256 "83c7e69c683ff5bccaa0a77749927a6fa8745c2ec61ef70287dfd3a84a2799cd"

      def install
        bin.install "uds-cli_v0.9.2_Darwin_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Darwin_amd64"
      sha256 "35e28e07e2756fba1f1eedd26c597e8bcda721e80f5278115fd68c5d3f7c9136"

      def install
        bin.install "uds-cli_v0.9.2_Darwin_amd64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Linux_amd64"
      sha256 "42757daf02e1dc683bf7885fd6218fba032b74da3d5ccd153a6996b5fb0b89a6"

      def install
        bin.install "uds-cli_v0.9.2_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.9.2/uds-cli_v0.9.2_Linux_arm64"
      sha256 "d32b78afd44a7e810a95f44f04afcae561565f91fcc2e14268ab5ccce7d90f28"

      def install
        bin.install "uds-cli_v0.9.2_Linux_arm64" => "uds"
      end
    end
  end
end
