# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT02716 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.27.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.16/uds-cli_v0.27.16_Darwin_amd64"
      sha256 "04cbb9cb11841eef5033a4c67acc5febb7d1fd52370171dc0c0e666e3907f405"

      def install
        bin.install "uds-cli_v0.27.16_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.16/uds-cli_v0.27.16_Darwin_arm64"
      sha256 "57f20c35fa0098fb88c9e3d65c282b39d112f88a8468d74beedaec985f061593"

      def install
        bin.install "uds-cli_v0.27.16_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.16/uds-cli_v0.27.16_Linux_amd64"
      sha256 "33899b9eede071b6a8ff78c9a60de3f100ab00eddeb29fe2b5e464b372592c27"
      def install
        bin.install "uds-cli_v0.27.16_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.16/uds-cli_v0.27.16_Linux_arm64"
      sha256 "37edc87a8c15eb5e3f90f8edfb115612ccc52b57f939efea0d66e675ed74a4b8"
      def install
        bin.install "uds-cli_v0.27.16_Linux_arm64" => "uds"
      end
    end
  end
end
