# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT020 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.2.0/uds-cli_v0.2.0_Darwin_arm64"
      sha256 "c5217f380ed351414e50d951cf8184c5baed3194fad7b07ee22e9906e86dbd6d"

      def install
        bin.install "uds-cli_v0.2.0_Darwin_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.2.0/uds-cli_v0.2.0_Darwin_amd64"
      sha256 "946390f18e164a8a9cf44d7da71dabfacc2ac5ec519f578fe12ac91a262d4dfb"

      def install
        bin.install "uds-cli_v0.2.0_Darwin_amd64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.2.0/uds-cli_v0.2.0_Linux_arm64"
      sha256 "877d66034572e09a87c38a4b91e099f584817104fd3b97cbc4f929734c1033d1"

      def install
        bin.install "uds-cli_v0.2.0_Linux_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.2.0/uds-cli_v0.2.0_Linux_amd64"
      sha256 "ee96d9565892876b70c9d0b0b8b0eff963ad3961a4b2160475f503eeba45b615"

      def install
        bin.install "uds-cli_v0.2.0_Linux_amd64" => "uds"
      end
    end
  end
end
