# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0283 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.28.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.28.3/uds-cli_v0.28.3_Darwin_amd64"
      sha256 "ffeeaa5a08ce5dfe2bde28ac3e1658b2b1dc94c05de8737a6f3c7c273cca3ca1"

      define_method(:install) do
        bin.install "uds-cli_v0.28.3_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.28.3/uds-cli_v0.28.3_Darwin_arm64"
      sha256 "aba30c9ad5c18403fbfb891677f10a56a41b9ad546bf842cc86154b45e1b87e9"

      define_method(:install) do
        bin.install "uds-cli_v0.28.3_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.28.3/uds-cli_v0.28.3_Linux_amd64"
      sha256 "07210dd8970017be7d3100682578ffa581732264b686646190c63cce9db42265"
      define_method(:install) do
        bin.install "uds-cli_v0.28.3_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.28.3/uds-cli_v0.28.3_Linux_arm64"
      sha256 "4b47cbe25480c8b2fcb3c864ca6ffe226a67b65c47fa5acb7d11ebf9f2bb8169"
      define_method(:install) do
        bin.install "uds-cli_v0.28.3_Linux_arm64" => "uds"
      end
    end
  end
end
