# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT02717 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.27.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.17/uds-cli_v0.27.17_Darwin_amd64"
      sha256 "1ca78adfa7bbf258468faf608e14699db160b10d7788d3492398245c39794d04"

      def install
        bin.install "uds-cli_v0.27.17_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.17/uds-cli_v0.27.17_Darwin_arm64"
      sha256 "ba89e714375bbb08a58d742e320c08c128bd3d1c69fbaa4e1626bb6721016788"

      def install
        bin.install "uds-cli_v0.27.17_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.17/uds-cli_v0.27.17_Linux_amd64"
      sha256 "19bf73f40b49358f8f3adbdc2587a214c13e9011d95bbec61e91d4615dd79123"
      def install
        bin.install "uds-cli_v0.27.17_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.27.17/uds-cli_v0.27.17_Linux_arm64"
      sha256 "f3dac5649981af2aee6d770b1f567fa71d814197e95ae3babb4239de4103a0bf"
      def install
        bin.install "uds-cli_v0.27.17_Linux_arm64" => "uds"
      end
    end
  end
end
