# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT008Alpha < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.0.8-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.8-alpha/uds-cli_v0.0.8-alpha_Darwin_arm64"
      sha256 "b3ff7f11d2532845219605c8a82185b20bd1195a8496d97be3c44fa6b6cd3964"

      def install
        bin.install "uds-cli_v0.0.8-alpha_Darwin_arm64" => "uds"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.8-alpha/uds-cli_v0.0.8-alpha_Darwin_amd64"
      sha256 "b12bfdc9385418f9455573a8b40b8597b9cce1ea4b51ef00acd9070b52bf68db"

      def install
        bin.install "uds-cli_v0.0.8-alpha_Darwin_amd64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.8-alpha/uds-cli_v0.0.8-alpha_Linux_amd64"
      sha256 "909b0c1a3fb89948fa11c4018f8cf7e973404e6cf2692df263e4819b6860e708"

      def install
        bin.install "uds-cli_v0.0.8-alpha_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.8-alpha/uds-cli_v0.0.8-alpha_Linux_arm64"
      sha256 "e1a720d47ff2a90758707291c3d9ae15228eeb957230ce15c2a26f7a341e7a37"

      def install
        bin.install "uds-cli_v0.0.8-alpha_Linux_arm64" => "uds"
      end
    end
  end
end
