# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0011Alpha < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.0.11-alpha"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.11-alpha/uds-cli_v0.0.11-alpha_Darwin_amd64"
      sha256 "5c15b17cad5ecfac304f2b59d5e73b6cd1ec5cfa58447f13a45dde1347c3e59b"

      def install
        bin.install "uds-cli_v0.0.11-alpha_Darwin_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.11-alpha/uds-cli_v0.0.11-alpha_Darwin_arm64"
      sha256 "19b45b3468d00752bf7228248a590bbf50a40e3722617e5e47afaf512206cb2b"

      def install
        bin.install "uds-cli_v0.0.11-alpha_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.11-alpha/uds-cli_v0.0.11-alpha_Linux_amd64"
      sha256 "88cb8554374438b3496c5d1b8eac44cd25e33b4fe3a8066b479353e456ebe0d9"

      def install
        bin.install "uds-cli_v0.0.11-alpha_Linux_amd64" => "uds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.0.11-alpha/uds-cli_v0.0.11-alpha_Linux_arm64"
      sha256 "cd1fb667b814d9a87991bd0e840e364218c371ab1bcbf00072dad5b72252a694"

      def install
        bin.install "uds-cli_v0.0.11-alpha_Linux_arm64" => "uds"
      end
    end
  end
end
