# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UdsAT0111 < Formula
  desc "CLI for Unicorn Delivery Service"
  homepage "https://github.com/defenseunicorns/uds-cli"
  version "0.11.1"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.1/uds-cli_v0.11.1_Darwin_amd64"
      sha256 "95e8eb4e65eb03ddc17db54bf431fad9ca60cb523bd2b9525ae2ae06331b7239"

      def install
        bin.install "uds-cli_v0.11.1_Darwin_amd64" => "uds"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.1/uds-cli_v0.11.1_Darwin_arm64"
      sha256 "3de87f14981a3ce75c27e6bd311d04ffce84e5a6fe39467ca64c1dbe86ceeebb"

      def install
        bin.install "uds-cli_v0.11.1_Darwin_arm64" => "uds"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.1/uds-cli_v0.11.1_Linux_amd64"
        sha256 "90d629866d62606805285509df5488402180b69489131ccdefe79a0a1f651a39"

        def install
          bin.install "uds-cli_v0.11.1_Linux_amd64" => "uds"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/uds-cli/releases/download/v0.11.1/uds-cli_v0.11.1_Linux_arm64"
        sha256 "0a0da4af6fd462ed96a2787dcdb9abbd6920d53f1ced0d5fc2f647e2df25c421"

        def install
          bin.install "uds-cli_v0.11.1_Linux_arm64" => "uds"
        end
      end
    end
  end
end
