# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0731 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.73.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.1/zarf_v0.73.1_Darwin_amd64"
      sha256 "074dbbc72ff2825893880d499560aa786266c691108dec376c7b60e6478037f6"

      define_method(:install) do
        bin.install "zarf_v0.73.1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.1/zarf_v0.73.1_Darwin_arm64"
      sha256 "7f9584103ae6e691c772176a02dba38684d662969c3bd102a2b4f97559c495cc"

      define_method(:install) do
        bin.install "zarf_v0.73.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.1/zarf_v0.73.1_Linux_amd64"
      sha256 "e27c94a5179fb40ba5f14195cf27964a28302dd1df8ce3620de02f872a8c51d9"
      define_method(:install) do
        bin.install "zarf_v0.73.1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.1/zarf_v0.73.1_Linux_arm64"
      sha256 "ca70c9be76d1e3375158636f657a9ee6a1cf7801b72acd3cab0ed311ca2d354f"
      define_method(:install) do
        bin.install "zarf_v0.73.1_Linux_arm64" => "zarf"
      end
    end
  end
end
