# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0380 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.38.0"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.38.0/zarf_v0.38.0_Darwin_amd64"
      sha256 "24743987b61a08c7edfc93d721fd4db016214a2254d6554d232a5cf7f0555f43"

      def install
        bin.install "zarf_v0.38.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.38.0/zarf_v0.38.0_Darwin_arm64"
      sha256 "7fefe56232f9896eb1105192fb741e4d2cba1b1450c6f1d41126d8616159ad15"

      def install
        bin.install "zarf_v0.38.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.38.0/zarf_v0.38.0_Linux_amd64"
        sha256 "0cef66723181d3197a4edfe894be7b4299d89a5c211e615ba79a24ed3f43aaa9"

        def install
          bin.install "zarf_v0.38.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.38.0/zarf_v0.38.0_Linux_arm64"
        sha256 "7326de48ecbe2ef9369ebdbc2e2d8f0758db7c4ce26384bd805541597c54791d"

        def install
          bin.install "zarf_v0.38.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
