# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0340 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.34.0"

  on_macos do
    on_intel do
      url "https://github.com/defenseunicorns/zarf/releases/download/v0.34.0/zarf_v0.34.0_Darwin_amd64"
      sha256 "28d3456463fbdf58b232b976da2f56dff7f4d928ef908409f39adfba2cc93c2e"

      def install
        bin.install "zarf_v0.34.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/defenseunicorns/zarf/releases/download/v0.34.0/zarf_v0.34.0_Darwin_arm64"
      sha256 "ab976da57d9c7e03e09b686f11a2a4841d854910c18132feec825ebd096f98a6"

      def install
        bin.install "zarf_v0.34.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/zarf/releases/download/v0.34.0/zarf_v0.34.0_Linux_amd64"
        sha256 "c7eba354ddccd3a65fbcfea1778df9f44c73facabc02dbaac42d006df01831ab"

        def install
          bin.install "zarf_v0.34.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/defenseunicorns/zarf/releases/download/v0.34.0/zarf_v0.34.0_Linux_arm64"
        sha256 "e1f3323b4e547e1eec560eedbae435164c05d5836d6f0ab8a07de8d4f9c8ed05"

        def install
          bin.install "zarf_v0.34.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
