# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0401 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.40.1"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.40.1/zarf_v0.40.1_Darwin_amd64"
      sha256 "797c340871c54400bb81d79dc2bb56a850d518e2f84bc2fff5f4e4a26f7a3596"

      def install
        bin.install "zarf_v0.40.1_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.40.1/zarf_v0.40.1_Darwin_arm64"
      sha256 "2286f6c70fbdbaab7d0ba3ea58f579eb1c8baa1327692bd94f7a2eed9808e96e"

      def install
        bin.install "zarf_v0.40.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.40.1/zarf_v0.40.1_Linux_amd64"
        sha256 "457e1d2a30027f81ce977436a0fefe15456b292d5e51bfac780e8fa3d1b9a5d7"

        def install
          bin.install "zarf_v0.40.1_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.40.1/zarf_v0.40.1_Linux_arm64"
        sha256 "fcbddfec33a22b81de344901edb6e4a84ac2774b7d01410bd086fdb2395737f5"

        def install
          bin.install "zarf_v0.40.1_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
