# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0510 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.51.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.51.0/zarf_v0.51.0_Darwin_amd64"
      sha256 "07f39735cc18f2dd0be08ced29452809028b07cc6c00b6ff5f6cc832cffba00f"

      def install
        bin.install "zarf_v0.51.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.51.0/zarf_v0.51.0_Darwin_arm64"
      sha256 "d4bd8b41fa8a10f8a44bd135a6137c9ae663f27bd1a22ae3949f0f8ff814c5df"

      def install
        bin.install "zarf_v0.51.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.51.0/zarf_v0.51.0_Linux_amd64"
        sha256 "378682c7db9bb0ca41b7b714840a3c78ce1fad7828f471d56727619e494a5662"

        def install
          bin.install "zarf_v0.51.0_Linux_amd64" => "zarf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.51.0/zarf_v0.51.0_Linux_arm64"
        sha256 "b2b93bd06d8ab83ae0e5aa8a7040af72fd88547f6d53dc77270aa76a398caeae"

        def install
          bin.install "zarf_v0.51.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
