# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0310Rc1 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.31.0-rc1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.31.0-rc1/zarf_v0.31.0-rc1_Darwin_arm64"
      sha256 "d3745b9f7b4ea0bd6d72c5e7656f270a74620495a28ff751c7c83004486331d5"

      def install
        bin.install "zarf_v0.31.0-rc1_Darwin_arm64" => "zarf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.31.0-rc1/zarf_v0.31.0-rc1_Darwin_amd64"
      sha256 "2df0fbfb3735fb52fd4c92290a0f2b3c00a0dce9ded0214f00f30d425cb2d2ee"

      def install
        bin.install "zarf_v0.31.0-rc1_Darwin_amd64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.31.0-rc1/zarf_v0.31.0-rc1_Linux_arm64"
      sha256 "c81241f21dd6b5cc9d24076ed019093688a22ed346578d11d6817a26f5c73b82"

      def install
        bin.install "zarf_v0.31.0-rc1_Linux_arm64" => "zarf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.31.0-rc1/zarf_v0.31.0-rc1_Linux_amd64"
      sha256 "3f4c97eb2d5890ec66ec11217df5561bcac1d3e101cba6fa00ced94adcde7687"

      def install
        bin.install "zarf_v0.31.0-rc1_Linux_amd64" => "zarf"
      end
    end
  end
end
