# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0440 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.44.0"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.44.0/zarf_v0.44.0_Darwin_amd64"
      sha256 "e9123e3a435066e54021887b60156a8654c60037b192665d3653a85db3a81a97"

      def install
        bin.install "zarf_v0.44.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.44.0/zarf_v0.44.0_Darwin_arm64"
      sha256 "72664ce5e49ebd443a26a036a56d5e551c10e3bb277ce7c0e6fea769b66f60af"

      def install
        bin.install "zarf_v0.44.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.44.0/zarf_v0.44.0_Linux_amd64"
        sha256 "752f44f15b7b801233f922bee449bf92e050475c81ec885415a3c3d8af55f59a"

        def install
          bin.install "zarf_v0.44.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.44.0/zarf_v0.44.0_Linux_arm64"
        sha256 "921ed89e714e8383291efe07fac78014ac03a70cdad737be78779e70fcfa3a69"

        def install
          bin.install "zarf_v0.44.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
