# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0560 < Formula
  desc "DevSecOps for Airgap"
  homepage "https://zarf.dev/"
  version "0.56.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.56.0/zarf_v0.56.0_Darwin_amd64"
      sha256 "407c5ddf380be941ac83292871f37df38af28314f9c0f28aa02da6369073f88e"

      def install
        bin.install "zarf_v0.56.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.56.0/zarf_v0.56.0_Darwin_arm64"
      sha256 "5df13940b14f57ba09dbd64e3b2342a74f0464093618bd1c2a4431bd57acd5b9"

      def install
        bin.install "zarf_v0.56.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.56.0/zarf_v0.56.0_Linux_amd64"
      sha256 "ced29ec9d5ed51411bf1415c7d4e52bc479caae543b5ebbe1f1d1810f50c1a9b"
      def install
        bin.install "zarf_v0.56.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.56.0/zarf_v0.56.0_Linux_arm64"
      sha256 "b5a6329e7c7ea18458c40608c61c940cf23ec36a064d156409d73d5bcdd84b12"
      def install
        bin.install "zarf_v0.56.0_Linux_arm64" => "zarf"
      end
    end
  end
end
