# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0670 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.67.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.67.0/zarf_v0.67.0_Darwin_amd64"
      sha256 "c86354317a760b3b295fb8f1b25cb627661f5e9d19416f13d28de3932556b26c"

      def install
        bin.install "zarf_v0.67.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.67.0/zarf_v0.67.0_Darwin_arm64"
      sha256 "2f85cbc52b1273468b70e94a9bbf5a71787302f60556cdc41ea62da1678bf9a8"

      def install
        bin.install "zarf_v0.67.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.67.0/zarf_v0.67.0_Linux_amd64"
      sha256 "b762abf3a75625a3bfa225ea925be54879442aa3d1d5869d340d8a0fd13f3f90"
      def install
        bin.install "zarf_v0.67.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.67.0/zarf_v0.67.0_Linux_arm64"
      sha256 "9baa497294c2cabfa637d79ff9655a7ba3a1ca2531d5103d78ef3606b226306a"
      def install
        bin.install "zarf_v0.67.0_Linux_arm64" => "zarf"
      end
    end
  end
end
