# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0370 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.37.0"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.37.0/zarf_v0.37.0_Darwin_amd64"
      sha256 "45d3bdf8e8af8f1e62e90256dbd7fdc1969cc1d0583a9d59f8c90f56f7448f7a"

      def install
        bin.install "zarf_v0.37.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.37.0/zarf_v0.37.0_Darwin_arm64"
      sha256 "54d5a7a07de65348c047505e8bc67118e0dcf63919368ee37a0a8248f21e0346"

      def install
        bin.install "zarf_v0.37.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.37.0/zarf_v0.37.0_Linux_amd64"
        sha256 "874c8b3290ad795989bd0de36721d2f556a9a6f058214159f64930d0a5079e20"

        def install
          bin.install "zarf_v0.37.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.37.0/zarf_v0.37.0_Linux_arm64"
        sha256 "6b22a7de93ca72c6a736bd61f08d657c8eec43f36121609e9592aea7de6e7390"

        def install
          bin.install "zarf_v0.37.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
