# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0460 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.46.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.46.0/zarf_v0.46.0_Darwin_amd64"
      sha256 "9fc0734627394f349a90f794f4cab19def70e30e5d5d1fec3eeddd793352abc0"

      def install
        bin.install "zarf_v0.46.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.46.0/zarf_v0.46.0_Darwin_arm64"
      sha256 "5afc2c2286cf8ef6bc2bf5f6f7fd236e381d2be38f7c0b884b98529e286b1ebe"

      def install
        bin.install "zarf_v0.46.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.46.0/zarf_v0.46.0_Linux_amd64"
        sha256 "602f76aad294fb66a463ddd9292d470218b404ee607e417e966ee6587afcde93"

        def install
          bin.install "zarf_v0.46.0_Linux_amd64" => "zarf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.46.0/zarf_v0.46.0_Linux_arm64"
        sha256 "1a3b291b4fa2bfa292a47b69e605d152aea62ddd361940728dfc374795b4a351"

        def install
          bin.install "zarf_v0.46.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
