# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0530Rc1 < Formula
  desc "DevSecOps for Airgap"
  homepage "https://zarf.dev/"
  version "0.53.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.53.0-rc1/zarf_v0.53.0-rc1_Darwin_amd64"
      sha256 "57fc7034f4468bf91f365982f381a43de9a195eb29534980f5aabc06f994229a"

      def install
        bin.install "zarf_v0.53.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.53.0-rc1/zarf_v0.53.0-rc1_Darwin_arm64"
      sha256 "04e771b0dc3cfdb05ff763445a5be4dee84a82c9cf68c8293bffe1aa9fc49d1b"

      def install
        bin.install "zarf_v0.53.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.53.0-rc1/zarf_v0.53.0-rc1_Linux_amd64"
        sha256 "ad0ccd51c777a33f5596292ff3e932e5d99133ea3d0d7b83928bd9eae703acdb"

        def install
          bin.install "zarf_v0.53.0-rc1_Linux_amd64" => "zarf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.53.0-rc1/zarf_v0.53.0-rc1_Linux_arm64"
        sha256 "d0792dd1189f74ea3cee109b5845bcb9f8f2e430b4c6896f5749fb4cbf107d95"

        def install
          bin.install "zarf_v0.53.0-rc1_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
