# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfRc < Formula
  desc "The Airgap Native Package Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.87.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.87.0-rc1/zarf_v0.87.0-rc1_Darwin_amd64"
      sha256 "9e7b9981c638cc13613a8480252b0d795a94e6be4bf1020fd65ff3ee2ef84a20"

      define_method(:install) do
        bin.install "zarf_v0.87.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.87.0-rc1/zarf_v0.87.0-rc1_Darwin_arm64"
      sha256 "21d9e9cd33c422fdcf1bf9788064cf0245ba31eaa241ae8fe23021fd96a45494"

      define_method(:install) do
        bin.install "zarf_v0.87.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.87.0-rc1/zarf_v0.87.0-rc1_Linux_amd64"
      sha256 "8c4c2ce12b46b30bba2375e1a1123a305e39f7accb9d795dae05218f505c5721"
      define_method(:install) do
        bin.install "zarf_v0.87.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.87.0-rc1/zarf_v0.87.0-rc1_Linux_arm64"
      sha256 "e6b375552d9a2e14c5c5c91657529a0ee7b334d1bb5da7c6e249a2cf882d7b11"
      define_method(:install) do
        bin.install "zarf_v0.87.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
