# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0760 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.76.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.76.0/zarf_v0.76.0_Darwin_amd64"
      sha256 "19d4c5941201a1b33627d8341d7b9a5384f261be0ff9e84102de0ec40f8b218c"

      define_method(:install) do
        bin.install "zarf_v0.76.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.76.0/zarf_v0.76.0_Darwin_arm64"
      sha256 "a43004efe2be00453e189fbd4d1a14add42c076b8604547caecd642beabb70dc"

      define_method(:install) do
        bin.install "zarf_v0.76.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.76.0/zarf_v0.76.0_Linux_amd64"
      sha256 "aba4ac2f48025858f26ae44771d59f36bcb469242ee3a3df66bf52b015ee554f"
      define_method(:install) do
        bin.install "zarf_v0.76.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.76.0/zarf_v0.76.0_Linux_arm64"
      sha256 "37096ae23f1fadd20485871dca5a7da16a1e653f7a7424933de84e305b13553f"
      define_method(:install) do
        bin.install "zarf_v0.76.0_Linux_arm64" => "zarf"
      end
    end
  end
end
