# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0491 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.49.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.49.1/zarf_v0.49.1_Darwin_amd64"
      sha256 "94cbb26d0b2030ce416354f225e7dd04c6aa227a350b955af57b515de02c5709"

      def install
        bin.install "zarf_v0.49.1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.49.1/zarf_v0.49.1_Darwin_arm64"
      sha256 "203f6a0061331a30625308cad60f2f58eaaea4e1f8fd968463d1a1f876f94120"

      def install
        bin.install "zarf_v0.49.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.49.1/zarf_v0.49.1_Linux_amd64"
        sha256 "8e77c8194a73fc82496f745f6517ef80f472560a574769eea8460d7d809c42eb"

        def install
          bin.install "zarf_v0.49.1_Linux_amd64" => "zarf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.49.1/zarf_v0.49.1_Linux_arm64"
        sha256 "3b6d45becb7c507a699c402744a84c578297b303716aff8e3078a3c479282722"

        def install
          bin.install "zarf_v0.49.1_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
