# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0720Rc1 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.72.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.72.0-rc1/zarf_v0.72.0-rc1_Darwin_amd64"
      sha256 "27cf5623dacdae90f703547fcbdf01f173f74c80746d9b5196a0bc3157391dc8"

      def install
        bin.install "zarf_v0.72.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.72.0-rc1/zarf_v0.72.0-rc1_Darwin_arm64"
      sha256 "7d06088301656a6ff03bcf814d9a6d4676762357d683a69957a48f5c8d5af2ce"

      def install
        bin.install "zarf_v0.72.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.72.0-rc1/zarf_v0.72.0-rc1_Linux_amd64"
      sha256 "58d3f9b8b043c78db9d309ad2062114a22cb8127375c4ed02077397dc42363d2"
      def install
        bin.install "zarf_v0.72.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.72.0-rc1/zarf_v0.72.0-rc1_Linux_arm64"
      sha256 "bd7a3fd475fba4cad3fca8f9ec9cca5531f30837f6a82bf33f1454559d8ef135"
      def install
        bin.install "zarf_v0.72.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
