# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0751Rc2 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.75.1-rc2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.1-rc2/zarf_v0.75.1-rc2_Darwin_amd64"
      sha256 "8ae390693486cf7940a2eb2ba420cf07222468c07431349fa27a3df8d39f5154"

      define_method(:install) do
        bin.install "zarf_v0.75.1-rc2_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.1-rc2/zarf_v0.75.1-rc2_Darwin_arm64"
      sha256 "7c99ada75153c79d208c5da1184744a497ea61fd78aa77c3698725dba14bf1fe"

      define_method(:install) do
        bin.install "zarf_v0.75.1-rc2_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.1-rc2/zarf_v0.75.1-rc2_Linux_amd64"
      sha256 "04399701c24adc2d4499e3079503108f264d05caa204f7ebc10b3570a8ef5cb1"
      define_method(:install) do
        bin.install "zarf_v0.75.1-rc2_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.1-rc2/zarf_v0.75.1-rc2_Linux_arm64"
      sha256 "8a8e7c6a43d67d970aeb63bfae92ce14f522fc86056681a59e1f30937c555503"
      define_method(:install) do
        bin.install "zarf_v0.75.1-rc2_Linux_arm64" => "zarf"
      end
    end
  end
end
