# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0860 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.86.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0/zarf_v0.86.0_Darwin_amd64"
      sha256 "1adf00be00a031b0298afd7fccaa33a10bd670c84995841a5765634879a1ae89"

      define_method(:install) do
        bin.install "zarf_v0.86.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0/zarf_v0.86.0_Darwin_arm64"
      sha256 "ba7705a324b3a4960a410a69dc57c347935827afd3a272512aaa234d66d85ca9"

      define_method(:install) do
        bin.install "zarf_v0.86.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0/zarf_v0.86.0_Linux_amd64"
      sha256 "ef05fcfa2121d2b8d152805c1269362ef214e48ec025ea5b08dc5970c8a3a77c"
      define_method(:install) do
        bin.install "zarf_v0.86.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0/zarf_v0.86.0_Linux_arm64"
      sha256 "574b3f23685338dd18e2bb6673fa58fab562ceb63c0a0bf7869cc5dc6f252056"
      define_method(:install) do
        bin.install "zarf_v0.86.0_Linux_arm64" => "zarf"
      end
    end
  end
end
