# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0262 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.26.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.26.2/zarf_v0.26.2_Darwin_amd64"
      sha256 "e79251f758b8b469f1ade2e3948ae0c45ac267dd0a038f08eb9f76f4979d73ad"

      def install
        bin.install "zarf_v0.26.2_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.26.2/zarf_v0.26.2_Darwin_arm64"
      sha256 "97964affa13cabc13a2e4a3b2fd7db00b11258c3846902f6d214b443613d5bb0"

      def install
        bin.install "zarf_v0.26.2_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.26.2/zarf_v0.26.2_Linux_arm64"
      sha256 "fc93b1b9d4aff0cc4d7d7ed80ecad2268ebe1b294f9ab3f9f3f0f7206ab6c6df"

      def install
        bin.install "zarf_v0.26.2_Linux_arm64" => "zarf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.26.2/zarf_v0.26.2_Linux_amd64"
      sha256 "2f0864f8c0951ce0d22b6ee06f0922d7d50a30eee356e89341f078056e84f259"

      def install
        bin.install "zarf_v0.26.2_Linux_amd64" => "zarf"
      end
    end
  end
end
