# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0450 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.45.0"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.45.0/zarf_v0.45.0_Darwin_amd64"
      sha256 "41fe865be3ee9139ed96ee9c3251cb9db7def2f3b03667ea7936f635ec1423c7"

      def install
        bin.install "zarf_v0.45.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.45.0/zarf_v0.45.0_Darwin_arm64"
      sha256 "8b72d4b10293b6397b207397fb1852151a4a4b10c1db33aa6164428ae61a2234"

      def install
        bin.install "zarf_v0.45.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.45.0/zarf_v0.45.0_Linux_amd64"
        sha256 "e567ae403d06d63416f38c3a12daa1b779b4574b9d443cac91d5aaea49d09e21"

        def install
          bin.install "zarf_v0.45.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.45.0/zarf_v0.45.0_Linux_arm64"
        sha256 "3bbda083245017fdd3a356e11840f4ea14497fa025ae2bca4bdc1df8853eb814"

        def install
          bin.install "zarf_v0.45.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
