# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0820 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.82.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.82.0/zarf_v0.82.0_Darwin_amd64"
      sha256 "f87cd8ffd80e9be339696e9d8d04613869b461408c39d88e4e4fbd0676e613f3"

      define_method(:install) do
        bin.install "zarf_v0.82.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.82.0/zarf_v0.82.0_Darwin_arm64"
      sha256 "44c64b7cca9b9ab7cbd5274773d070e9d7bb397e9c667269b21f28669265afc8"

      define_method(:install) do
        bin.install "zarf_v0.82.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.82.0/zarf_v0.82.0_Linux_amd64"
      sha256 "e372002110600a458ca2a9222a34b8cdebc9c0fcd81d7e34febd3d8411d7beaf"
      define_method(:install) do
        bin.install "zarf_v0.82.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.82.0/zarf_v0.82.0_Linux_arm64"
      sha256 "01a61c47d9ffc7b78dc84052108cc755d7fbc1281450268bd290a00f610b1c65"
      define_method(:install) do
        bin.install "zarf_v0.82.0_Linux_arm64" => "zarf"
      end
    end
  end
end
