# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0490 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.49.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.49.0/zarf_v0.49.0_Darwin_amd64"
      sha256 "4fae3cbc8bdbafdb8cd657057cbc92130d029c45e38a310d0daa4555d16ec865"

      def install
        bin.install "zarf_v0.49.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.49.0/zarf_v0.49.0_Darwin_arm64"
      sha256 "d065ec4b8a6276ede36fe06b14c78f7fc7b4b2d70f38b46de6cea73d345b6cec"

      def install
        bin.install "zarf_v0.49.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.49.0/zarf_v0.49.0_Linux_amd64"
        sha256 "614986ce168e55c3c5250e673f8d7ee1f23dd8a755e6736b6eac6a3a5ac48549"

        def install
          bin.install "zarf_v0.49.0_Linux_amd64" => "zarf"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.49.0/zarf_v0.49.0_Linux_arm64"
        sha256 "a852bef5cb8c09c4aa144fe372def1e1a2953242c56506999a25d27ab9c90b11"

        def install
          bin.install "zarf_v0.49.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
