# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0750 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.75.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.0/zarf_v0.75.0_Darwin_amd64"
      sha256 "39cf4fd291947cda8482ca55a29d67da56b812194bc8b9683d6e215ae0d3ba1c"

      define_method(:install) do
        bin.install "zarf_v0.75.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.0/zarf_v0.75.0_Darwin_arm64"
      sha256 "7b71bc68a97a0b1dbbc4b16c79a592f4ac9785e33a149e121f8e6014602241c3"

      define_method(:install) do
        bin.install "zarf_v0.75.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.0/zarf_v0.75.0_Linux_amd64"
      sha256 "8c985140177b76b1817503320603ad6041e6520de0f0fbabf674aa1bb3991b21"
      define_method(:install) do
        bin.install "zarf_v0.75.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.75.0/zarf_v0.75.0_Linux_arm64"
      sha256 "91b9e2868ff1557df672a7b68a0cac5da6833265466e317a5926810aeebd2fab"
      define_method(:install) do
        bin.install "zarf_v0.75.0_Linux_arm64" => "zarf"
      end
    end
  end
end
