# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0410 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.41.0"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.41.0/zarf_v0.41.0_Darwin_amd64"
      sha256 "2bae8bbf60bc5ead5f2a405dc76f0a184ec9500b17ac7acd29d4fb3119d8deb3"

      def install
        bin.install "zarf_v0.41.0_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.41.0/zarf_v0.41.0_Darwin_arm64"
      sha256 "6da7475047db3caebdcee674aa7d204dd97496d61a623151318bc8ff38950909"

      def install
        bin.install "zarf_v0.41.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.41.0/zarf_v0.41.0_Linux_amd64"
        sha256 "d03e56a2fa9e08b12df314a868b84e7ab75ec6fa0f57cb6d899637aa387171ce"

        def install
          bin.install "zarf_v0.41.0_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.41.0/zarf_v0.41.0_Linux_arm64"
        sha256 "861d1b241cb4980d1f677994efd636688349841847508c589b588971e86b2c94"

        def install
          bin.install "zarf_v0.41.0_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
