# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0600Rc1 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.60.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.60.0-rc1/zarf_v0.60.0-rc1_Darwin_amd64"
      sha256 "feb34f37c9ed280c123be15a7945872a1c7427eb7355fd6c6a06dea4041afa18"

      def install
        bin.install "zarf_v0.60.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.60.0-rc1/zarf_v0.60.0-rc1_Darwin_arm64"
      sha256 "bc806d56067bb17a74dd82e5d36996aca2127b1a7b794ae4a352fea0149ff2dd"

      def install
        bin.install "zarf_v0.60.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.60.0-rc1/zarf_v0.60.0-rc1_Linux_amd64"
      sha256 "a96f945414b40ca6b3556826b5b6d9c0624cb737adc66305b5658232b6ea4d03"
      def install
        bin.install "zarf_v0.60.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.60.0-rc1/zarf_v0.60.0-rc1_Linux_arm64"
      sha256 "a4573db2d729e04b21ef217cdbe726ce6b8c23433d43b978ea9decc4e8497715"
      def install
        bin.install "zarf_v0.60.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
