# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0324 < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.32.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.32.4/zarf_v0.32.4_Darwin_arm64"
      sha256 "750731d55372c8d4e523cdecbdb6dc651d3d360696b00164effbdad081d32df1"

      def install
        bin.install "zarf_v0.32.4_Darwin_arm64" => "zarf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.32.4/zarf_v0.32.4_Darwin_amd64"
      sha256 "a33fa7170ad0c5af9908785945693da27f25ed01ff8684891a80125a300b15a9"

      def install
        bin.install "zarf_v0.32.4_Darwin_amd64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.32.4/zarf_v0.32.4_Linux_amd64"
      sha256 "9f4283ce66842a3c24083d13c6e4cbd94ba556e959ba84c22b49ff2a47b6363a"

      def install
        bin.install "zarf_v0.32.4_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.32.4/zarf_v0.32.4_Linux_arm64"
      sha256 "7a14ed53fbc67f3f46fba9b0180f9779c1c1c3486ef148c54e734e88b42beecf"

      def install
        bin.install "zarf_v0.32.4_Linux_arm64" => "zarf"
      end
    end
  end
end
