# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zarf@latestRc < Formula
  desc "DevSecOps for Airgap"
  homepage "https://zarf.dev/"
  version "0.58.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.58.0-rc1/zarf_v0.58.0-rc1_Darwin_amd64"
      sha256 "8835ef6034fa939651c05caeb7c4a0bfe2e85d21da40bc0cae3ccd568f775a22"

      def install
        bin.install "zarf_v0.58.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.58.0-rc1/zarf_v0.58.0-rc1_Darwin_arm64"
      sha256 "03cde38aab3bd7862b85b28f32f29587a8465ab668a3d2043f2d5df6bd57dc94"

      def install
        bin.install "zarf_v0.58.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.58.0-rc1/zarf_v0.58.0-rc1_Linux_amd64"
      sha256 "b9a40a77236ba811a31c57940b0ad44a346b7fa783434c6a4817ef64006a0938"
      def install
        bin.install "zarf_v0.58.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.58.0-rc1/zarf_v0.58.0-rc1_Linux_arm64"
      sha256 "e035f78000ad6ab8303663025d2db2c989b8d8819c8678f16cf9638f1b7e3afb"
      def install
        bin.install "zarf_v0.58.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
