# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0730 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.73.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.0/zarf_v0.73.0_Darwin_amd64"
      sha256 "41c6f78fe0482cebe2685614c5102cbf1ef66d35f849a82fe3a94975ab62e7de"

      def install
        bin.install "zarf_v0.73.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.0/zarf_v0.73.0_Darwin_arm64"
      sha256 "b8b4c74fd584592145e4cf0ae9d8025dd702f7ad5d47fdb171bd93ec259b8198"

      def install
        bin.install "zarf_v0.73.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.0/zarf_v0.73.0_Linux_amd64"
      sha256 "d6777f6d654f1088339060527cd5a67ecbd95a1037a816180cb1cc94f2c38db9"
      def install
        bin.install "zarf_v0.73.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.73.0/zarf_v0.73.0_Linux_arm64"
      sha256 "c4239a4947e680a1a8e5e1a4a2db6a7d921265ad1aa85aeb1d6cd18d8bb67e60"
      def install
        bin.install "zarf_v0.73.0_Linux_arm64" => "zarf"
      end
    end
  end
end
