# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0570 < Formula
  desc "DevSecOps for Airgap"
  homepage "https://zarf.dev/"
  version "0.57.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.57.0/zarf_v0.57.0_Darwin_amd64"
      sha256 "e057340cd4c985ce5212ad416aed273be539af3580eb563111efe171cec415a7"

      def install
        bin.install "zarf_v0.57.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.57.0/zarf_v0.57.0_Darwin_arm64"
      sha256 "9b43269c4ddc4efcd8af6222dc34b1e95ab8c31f274f46b21fbdf93d5a528535"

      def install
        bin.install "zarf_v0.57.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.57.0/zarf_v0.57.0_Linux_amd64"
      sha256 "edea299ea1ee35c50957b5a0e20554a6c567c4b70153e678b3a2cddecbeb3548"
      def install
        bin.install "zarf_v0.57.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.57.0/zarf_v0.57.0_Linux_arm64"
      sha256 "72226f4d65911274b0d33274686ce5aad96fce9d720821d4a14cfc0916f7ecac"
      def install
        bin.install "zarf_v0.57.0_Linux_arm64" => "zarf"
      end
    end
  end
end
