# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0611 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.61.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.61.1/zarf_v0.61.1_Darwin_amd64"
      sha256 "061b11891e350b514f6b11efea7d5d39639b48ef2e4905fd930c021b91bd9abd"

      def install
        bin.install "zarf_v0.61.1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.61.1/zarf_v0.61.1_Darwin_arm64"
      sha256 "b127dde294dc30adff9f2e9618b69cea052e0d64bf69ba7a3d7942e6da8c699e"

      def install
        bin.install "zarf_v0.61.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.61.1/zarf_v0.61.1_Linux_amd64"
      sha256 "ffc480cf2cb0ac7081540dd0523160bf87904359f068258b9c303ffe1b7c35c6"
      def install
        bin.install "zarf_v0.61.1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.61.1/zarf_v0.61.1_Linux_arm64"
      sha256 "f85ef70e28f5050e1f3e3edca7f4e4ad88c7e6dd895324297361c60438017316"
      def install
        bin.install "zarf_v0.61.1_Linux_arm64" => "zarf"
      end
    end
  end
end
