# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0711 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.71.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.71.1/zarf_v0.71.1_Darwin_amd64"
      sha256 "9fcc6f58a284843dba604a24aa3d16b2dab8ad775ee7aa04f70b281f30c328a0"

      def install
        bin.install "zarf_v0.71.1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.71.1/zarf_v0.71.1_Darwin_arm64"
      sha256 "bb41628dda85fc83a5e3e9e4c0d83b3b98119f17e30ef14cb4788655d94229f7"

      def install
        bin.install "zarf_v0.71.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.71.1/zarf_v0.71.1_Linux_amd64"
      sha256 "d271ee1fbb2588c39376f0cdd28a176759597880dd28eaa156af1b1b2223165f"
      def install
        bin.install "zarf_v0.71.1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.71.1/zarf_v0.71.1_Linux_arm64"
      sha256 "bb76e3eae2f198fb52ddc38cef701bd97380f07cb8081da972477a82f14a11d1"
      def install
        bin.install "zarf_v0.71.1_Linux_arm64" => "zarf"
      end
    end
  end
end
