# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Zarf < Formula
  desc "DevSecOps for Air Gap"
  homepage "https://zarf.dev/"
  version "0.42.1"

  on_macos do
    on_intel do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.42.1/zarf_v0.42.1_Darwin_amd64"
      sha256 "8722b6544ccb275f62d5c770c96a774af369d5155ce7f10b13e65c3d19d9b451"

      def install
        bin.install "zarf_v0.42.1_Darwin_amd64" => "zarf"
      end
    end
    on_arm do
      url "https://github.com/zarf-dev/zarf/releases/download/v0.42.1/zarf_v0.42.1_Darwin_arm64"
      sha256 "6c0bd3920ea1cb255bb48b06ce7d5c1a5e76203759aebaa7fd095822d8d92773"

      def install
        bin.install "zarf_v0.42.1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.42.1/zarf_v0.42.1_Linux_amd64"
        sha256 "49f705d335939cd8b1537260806e9defd90ba27e7f048ffd2aae53f32d7be00b"

        def install
          bin.install "zarf_v0.42.1_Linux_amd64" => "zarf"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zarf-dev/zarf/releases/download/v0.42.1/zarf_v0.42.1_Linux_arm64"
        sha256 "05b32ce29a2f6df88f24b8511d2616d0671285537655b638f6e4fb0f8ad5187f"

        def install
          bin.install "zarf_v0.42.1_Linux_arm64" => "zarf"
        end
      end
    end
  end
end
