# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0840 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.84.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.84.0/zarf_v0.84.0_Darwin_amd64"
      sha256 "965e985046db6b3b7821ff42896337f5e1bb3ada32772c7f7018a0859fe06092"

      define_method(:install) do
        bin.install "zarf_v0.84.0_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.84.0/zarf_v0.84.0_Darwin_arm64"
      sha256 "959974f60121e23907af9020f9a52da9ebd8587f21183a3b6c8cf12ee34c8296"

      define_method(:install) do
        bin.install "zarf_v0.84.0_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.84.0/zarf_v0.84.0_Linux_amd64"
      sha256 "9c632ca63d4aaad4a238ebb04b8a2e8e99f806a545a62196e3c4418ebd7dd48b"
      define_method(:install) do
        bin.install "zarf_v0.84.0_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.84.0/zarf_v0.84.0_Linux_arm64"
      sha256 "328997f0d7a72550ce5985efc93cbc8d4ebb7b7c147c08e3fdbebc441c3a9d6a"
      define_method(:install) do
        bin.install "zarf_v0.84.0_Linux_arm64" => "zarf"
      end
    end
  end
end
