# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfAT0650Rc1 < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.65.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.65.0-rc1/zarf_v0.65.0-rc1_Darwin_amd64"
      sha256 "8ddadc088b8106dc5315c931aa297eac9aa38e33ab4f26a234893356324db925"

      def install
        bin.install "zarf_v0.65.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.65.0-rc1/zarf_v0.65.0-rc1_Darwin_arm64"
      sha256 "a70a7732492d6593af5503bfc541249405d334d3c23f3926b0dc22ba1fdcaa0f"

      def install
        bin.install "zarf_v0.65.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.65.0-rc1/zarf_v0.65.0-rc1_Linux_amd64"
      sha256 "813a0685f0fa55aced3f5dd7b0903124cd8df7b37235ab9cdfd856f1df83b589"
      def install
        bin.install "zarf_v0.65.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.65.0-rc1/zarf_v0.65.0-rc1_Linux_arm64"
      sha256 "5f7ded90b5931d70a47651a6e9e5b4b130e18dcb20f94e4455fb42a1cf6090b7"
      def install
        bin.install "zarf_v0.65.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
