# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ZarfRc < Formula
  desc "The Airgap Native Packager Manager for Kubernetes"
  homepage "https://zarf.dev/"
  version "0.86.0-rc1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0-rc1/zarf_v0.86.0-rc1_Darwin_amd64"
      sha256 "4dd88bfe2cc46ad4ab19e6578b8ff3e08f1773189703857cfd7b3366f5962040"

      define_method(:install) do
        bin.install "zarf_v0.86.0-rc1_Darwin_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0-rc1/zarf_v0.86.0-rc1_Darwin_arm64"
      sha256 "6f0c9f44dcf4c1d7e999cdfbf22dd4df0afac1b2bbc894b4e16072725830c4c9"

      define_method(:install) do
        bin.install "zarf_v0.86.0-rc1_Darwin_arm64" => "zarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0-rc1/zarf_v0.86.0-rc1_Linux_amd64"
      sha256 "b58f8a2776359da1054dcd54616e15d07118bdabec78c50bf7176f1b98ae6f26"
      define_method(:install) do
        bin.install "zarf_v0.86.0-rc1_Linux_amd64" => "zarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zarf-dev/zarf/releases/download/v0.86.0-rc1/zarf_v0.86.0-rc1_Linux_arm64"
      sha256 "02eabfec8acffb09b5187738dfab7796f6ceec1b1df5d192d2b890b78b707981"
      define_method(:install) do
        bin.install "zarf_v0.86.0-rc1_Linux_arm64" => "zarf"
      end
    end
  end
end
